# Generated by Django 5.0.2 on 2024-03-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_tags_alter_scope_article_alter_scope_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='is_main',
            new_name='ОСНОВНОЙ',
        ),
    ]
