# Generated by Django 5.0.2 on 2024-03-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_is_main_scope_основной'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='РАЗДЕЛ',
        ),
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together=set(),
        ),
    ]
