# Generated by Django 5.0.2 on 2024-03-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_tag_scope_раздел_alter_scope_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='РАЗДЕЛ',
            new_name='tag',
        ),
    ]
