# Generated by Django 5.0.2 on 2024-03-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_tag_options_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'ТЕМАТИКИ СТАТЕЙ'},
        ),
    ]
