# Generated by Django 5.0.2 on 2024-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='ОСНОВНОЙ',
        ),
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='ОСНОВНОЙ'),
        ),
    ]
