# Generated by Django 5.0.2 on 2024-03-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_remove_scope_основной_scope_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
