# Generated by Django 5.0.2 on 2024-03-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
    ]
